# Local Development Database
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace_db
spring.datasource.username=postgres
spring.datasource.password=Kenzi2401

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AWS (use dummy values locally, or comment out if not needed)
aws.access.key.id=dummy
aws.secret.access.key=dummy
aws.s3.bucket.name=dummy
aws.s3.region=us-east-1

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=AKIAUSEFHM3ZLWMK5BVZ
spring.mail.password=BNkqVxXrMGKdbkZ4/uzbFRDVi90aEYC286qRdOH0xTc8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# App settings
app.email.from=noreply@yourmarketplace.com
app.name=Your Marketplace