spring.application.name=hope
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
server.port=5000

aws.access.key.id=test-key
aws.secret.access.key=test-secret
aws.s3.region=us-east-1
aws.s3.bucket.name=test-bucket